# NOT USED
# because cannot communicate from BitBucket to EC2 instances

image:
  name: 123456789012.dkr.ecr.us-east-1.amazonaws.com/sre-team/imagebuilder:1.3
  aws: 
   access-key: $AWS_ACCESS_KEY_ID
   secret-key: $AWS_SECRET_ACCESS_KEY

pipelines:
  # To set a whole pipeline to run manually, use a custom pipeline trigger.
  custom:
    build-custom:
      # https://support.atlassian.com/bitbucket-cloud/docs/step-options/
      - step:
          name: Packer Validate
          script:
            - packer validate -var-file vars/sharedservices.json -var-file vars/centos8.json -var-file vars/accounts.json base-centos8.json
            - packer validate -var-file vars/sharedservices.json -var-file vars/rhel7.json -var-file vars/accounts.json base-rhel7.json
            - packer validate -var-file vars/sharedservices.json -var-file vars/rhel8.json -var-file vars/accounts.json base-rhel8.json
            - packer validate -var-file vars/sharedservices.json -var-file vars/win2022.json -var-file vars/accounts.json base-windows.json
            - packer validate -var-file vars/sharedservices.json -var-file vars/win2019.json -var-file vars/accounts.json base-windows.json
            - packer validate -var-file vars/sharedservices.json -var-file vars/win2016.json -var-file vars/accounts.json base-windows.json
      - step:
          name: Ansible Lint
          script:
            - ansible-lint -w 208 ansible/linux7.yml
            - ansible-lint -w 208 ansible/linux8.yml
            - ansible-lint -w 208 ansible/windows.yml
            - ansible-lint ansible/clean_old_golden_amis.yml
      - parallel:
          - step:
              name: Build CentOS 8 AMI
              script:
                - packer build -timestamp-ui -var-file vars/sharedservices.json -var-file vars/centos8.json -var-file vars/accounts.json base-centos8.json
          - step:
              name: Build RHEL 7 AMI
              script:
                - packer build -timestamp-ui -var-file vars/sharedservices.json -var-file vars/rhel7.json -var-file vars/accounts.json base-rhel7.json
          - step:
              name: Build RHEL 8 AMI
              script:
                - packer build -timestamp-ui -var-file vars/sharedservices.json -var-file vars/rhel8.json -var-file vars/accounts.json base-rhel8.json
          - step:
              name: Build Windows Server 2022 AMI
              script:
                - packer build -timestamp-ui -var-file vars/sharedservices.json -var-file vars/win2022.json -var-file vars/accounts.json base-windows.json
          - step:
              name: Build Windows Server 2019 AMI
              script:
                - packer build -timestamp-ui -var-file vars/sharedservices.json -var-file vars/win2019.json -var-file vars/accounts.json base-windows.json
      - step:
          name: Clean Old AMIs
          script:
            - ansible-playbook ansible/clean_old_golden_amis.yml --extra-vars "ec2_region=us-east-1"
            - ansible-playbook ansible/clean_old_golden_amis.yml --extra-vars "ec2_region=ca-central-1"
          